variables:
    PLUGIN_NAME: 'dataverse'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/unit_tests.yml'
      - 'templates/groups/ojs/cypress_tests.yml'

.integration_tests_template:
  before_script:
    - sed -i "s/api_key_secret = \"\"/api_key_secret = \"$API_KEY_SECRET\"/" /var/www/$APPLICATION/config.inc.php
    - sed -n '/api_key_secret/p' /var/www/$APPLICATION/config.inc.php
