variables:
    PLUGIN_NAME: 'dataverse'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops_plugins_unit_tests_model.yml'
      - 'templates/groups/ojs_plugins_cypress_tests_model.yml'
      - 'templates/groups/ops_plugins_cypress_tests_model.yml'
